generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class:           DmUser
    theme: dmAdmin
    non_verbose_templates: true
    with_show:             false
    route_prefix:          dm_user
    with_doctrine_route:   true

    config:
      fields:
        groups_list:
          label: Groups
        permissions_list:
          label: Permissions
        is_active:
          label: Active
        is_super_admin:
          label: 'Super admin'
        password_again: { label: "Password (again)" }

      list:
        display:
          - id
          - =username
          - nombre
          - apellidos
          - email
          - solapin
          - departamento		  
          - foto_id
          - titulo 
          - is_active
          - is_super_admin
          - last_login
          - penalizado
          - created_at
          - updated_at
        sort:
          - nombre
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        loremize: false
      filter:
        display:
          - id
          - username
          - nombre
          - apellidos
          - email
          - is_active
          - last_login
          - penalizado
          - solapin
          - titulo
      form:
        display:
          NONE: [username, email, password, password_again, is_active, is_super_admin]
          "Groups & Permissions": [groups_list, permissions_list]
          "Datos del trabajador": [titulo,  foto_id_form, nombre, apellidos, foto_id_view, penalizado, solapin, departamento]
        fields:
          username: {label: Usuario}
        class: DmUserAdminForm